spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cxx1990/config-repo
          username: cxx1990317
          password: 15056040008cxx
          basedir: H:\springcloud\springcloud\config\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 7081
